environment:
  max_rounds: 10
  max_limit_bid: None
  min_limit_bid: None
  initial_prices: None
  num_bidders: None
  possible_agents: None
testing:
  num_games: 500
  render_mode: test
evaluation:
  render_mode: human
training:
  batch_size: 512
  ent_coef: 0.9
  learning_rate: 0.001
  seed: 42
  steps: 200
model_path: models/test

