environment:
  num_bidders: 4
  max_rounds: 20
  avg_min: 30


training:
  steps: 600_000
  learning_rate: 0.001
  seed: 42
  batch_size: 256
  ent_coef: 0.5

evaluation:
  num_games: 1
  render_mode: "human"